/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-8-12 下午3:34' with Gradle 2.9
 *
 * @author Administrator, @date 16-8-12 下午3:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
