// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.jokerbee.protocol;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aft.PlayerLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code aft.PlayerLogin}
   */
  public  static final class PlayerLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aft.PlayerLogin)
      PlayerLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerLogin.newBuilder() to construct.
    private PlayerLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerLogin() {
      account_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jokerbee.protocol.Game.internal_static_aft_PlayerLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jokerbee.protocol.Game.internal_static_aft_PlayerLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jokerbee.protocol.Game.PlayerLogin.class, com.jokerbee.protocol.Game.PlayerLogin.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jokerbee.protocol.Game.PlayerLogin)) {
        return super.equals(obj);
      }
      com.jokerbee.protocol.Game.PlayerLogin other = (com.jokerbee.protocol.Game.PlayerLogin) obj;

      boolean result = true;
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PlayerLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jokerbee.protocol.Game.PlayerLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aft.PlayerLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aft.PlayerLogin)
        com.jokerbee.protocol.Game.PlayerLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jokerbee.protocol.Game.internal_static_aft_PlayerLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jokerbee.protocol.Game.internal_static_aft_PlayerLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jokerbee.protocol.Game.PlayerLogin.class, com.jokerbee.protocol.Game.PlayerLogin.Builder.class);
      }

      // Construct using com.jokerbee.protocol.Game.PlayerLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        account_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jokerbee.protocol.Game.internal_static_aft_PlayerLogin_descriptor;
      }

      public com.jokerbee.protocol.Game.PlayerLogin getDefaultInstanceForType() {
        return com.jokerbee.protocol.Game.PlayerLogin.getDefaultInstance();
      }

      public com.jokerbee.protocol.Game.PlayerLogin build() {
        com.jokerbee.protocol.Game.PlayerLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jokerbee.protocol.Game.PlayerLogin buildPartial() {
        com.jokerbee.protocol.Game.PlayerLogin result = new com.jokerbee.protocol.Game.PlayerLogin(this);
        result.account_ = account_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jokerbee.protocol.Game.PlayerLogin) {
          return mergeFrom((com.jokerbee.protocol.Game.PlayerLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jokerbee.protocol.Game.PlayerLogin other) {
        if (other == com.jokerbee.protocol.Game.PlayerLogin.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jokerbee.protocol.Game.PlayerLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jokerbee.protocol.Game.PlayerLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aft.PlayerLogin)
    }

    // @@protoc_insertion_point(class_scope:aft.PlayerLogin)
    private static final com.jokerbee.protocol.Game.PlayerLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jokerbee.protocol.Game.PlayerLogin();
    }

    public static com.jokerbee.protocol.Game.PlayerLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerLogin>
        PARSER = new com.google.protobuf.AbstractParser<PlayerLogin>() {
      public PlayerLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerLogin> getParserForType() {
      return PARSER;
    }

    public com.jokerbee.protocol.Game.PlayerLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aft.PositionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 posX = 1;</code>
     */
    int getPosX();

    /**
     * <code>int32 posY = 2;</code>
     */
    int getPosY();

    /**
     * <code>int32 faceTo = 3;</code>
     */
    int getFaceTo();
  }
  /**
   * Protobuf type {@code aft.PositionInfo}
   */
  public  static final class PositionInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aft.PositionInfo)
      PositionInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionInfo.newBuilder() to construct.
    private PositionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionInfo() {
      posX_ = 0;
      posY_ = 0;
      faceTo_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              posX_ = input.readInt32();
              break;
            }
            case 16: {

              posY_ = input.readInt32();
              break;
            }
            case 24: {

              faceTo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jokerbee.protocol.Game.internal_static_aft_PositionInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jokerbee.protocol.Game.internal_static_aft_PositionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jokerbee.protocol.Game.PositionInfo.class, com.jokerbee.protocol.Game.PositionInfo.Builder.class);
    }

    public static final int POSX_FIELD_NUMBER = 1;
    private int posX_;
    /**
     * <code>int32 posX = 1;</code>
     */
    public int getPosX() {
      return posX_;
    }

    public static final int POSY_FIELD_NUMBER = 2;
    private int posY_;
    /**
     * <code>int32 posY = 2;</code>
     */
    public int getPosY() {
      return posY_;
    }

    public static final int FACETO_FIELD_NUMBER = 3;
    private int faceTo_;
    /**
     * <code>int32 faceTo = 3;</code>
     */
    public int getFaceTo() {
      return faceTo_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (posX_ != 0) {
        output.writeInt32(1, posX_);
      }
      if (posY_ != 0) {
        output.writeInt32(2, posY_);
      }
      if (faceTo_ != 0) {
        output.writeInt32(3, faceTo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (posX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, posX_);
      }
      if (posY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, posY_);
      }
      if (faceTo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, faceTo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jokerbee.protocol.Game.PositionInfo)) {
        return super.equals(obj);
      }
      com.jokerbee.protocol.Game.PositionInfo other = (com.jokerbee.protocol.Game.PositionInfo) obj;

      boolean result = true;
      result = result && (getPosX()
          == other.getPosX());
      result = result && (getPosY()
          == other.getPosY());
      result = result && (getFaceTo()
          == other.getFaceTo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSX_FIELD_NUMBER;
      hash = (53 * hash) + getPosX();
      hash = (37 * hash) + POSY_FIELD_NUMBER;
      hash = (53 * hash) + getPosY();
      hash = (37 * hash) + FACETO_FIELD_NUMBER;
      hash = (53 * hash) + getFaceTo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.PositionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jokerbee.protocol.Game.PositionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aft.PositionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aft.PositionInfo)
        com.jokerbee.protocol.Game.PositionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jokerbee.protocol.Game.internal_static_aft_PositionInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jokerbee.protocol.Game.internal_static_aft_PositionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jokerbee.protocol.Game.PositionInfo.class, com.jokerbee.protocol.Game.PositionInfo.Builder.class);
      }

      // Construct using com.jokerbee.protocol.Game.PositionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        posX_ = 0;

        posY_ = 0;

        faceTo_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jokerbee.protocol.Game.internal_static_aft_PositionInfo_descriptor;
      }

      public com.jokerbee.protocol.Game.PositionInfo getDefaultInstanceForType() {
        return com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance();
      }

      public com.jokerbee.protocol.Game.PositionInfo build() {
        com.jokerbee.protocol.Game.PositionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jokerbee.protocol.Game.PositionInfo buildPartial() {
        com.jokerbee.protocol.Game.PositionInfo result = new com.jokerbee.protocol.Game.PositionInfo(this);
        result.posX_ = posX_;
        result.posY_ = posY_;
        result.faceTo_ = faceTo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jokerbee.protocol.Game.PositionInfo) {
          return mergeFrom((com.jokerbee.protocol.Game.PositionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jokerbee.protocol.Game.PositionInfo other) {
        if (other == com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance()) return this;
        if (other.getPosX() != 0) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0) {
          setPosY(other.getPosY());
        }
        if (other.getFaceTo() != 0) {
          setFaceTo(other.getFaceTo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jokerbee.protocol.Game.PositionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jokerbee.protocol.Game.PositionInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int posX_ ;
      /**
       * <code>int32 posX = 1;</code>
       */
      public int getPosX() {
        return posX_;
      }
      /**
       * <code>int32 posX = 1;</code>
       */
      public Builder setPosX(int value) {
        
        posX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 posX = 1;</code>
       */
      public Builder clearPosX() {
        
        posX_ = 0;
        onChanged();
        return this;
      }

      private int posY_ ;
      /**
       * <code>int32 posY = 2;</code>
       */
      public int getPosY() {
        return posY_;
      }
      /**
       * <code>int32 posY = 2;</code>
       */
      public Builder setPosY(int value) {
        
        posY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 posY = 2;</code>
       */
      public Builder clearPosY() {
        
        posY_ = 0;
        onChanged();
        return this;
      }

      private int faceTo_ ;
      /**
       * <code>int32 faceTo = 3;</code>
       */
      public int getFaceTo() {
        return faceTo_;
      }
      /**
       * <code>int32 faceTo = 3;</code>
       */
      public Builder setFaceTo(int value) {
        
        faceTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 faceTo = 3;</code>
       */
      public Builder clearFaceTo() {
        
        faceTo_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aft.PositionInfo)
    }

    // @@protoc_insertion_point(class_scope:aft.PositionInfo)
    private static final com.jokerbee.protocol.Game.PositionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jokerbee.protocol.Game.PositionInfo();
    }

    public static com.jokerbee.protocol.Game.PositionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionInfo>
        PARSER = new com.google.protobuf.AbstractParser<PositionInfo>() {
      public PositionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionInfo> getParserForType() {
      return PARSER;
    }

    public com.jokerbee.protocol.Game.PositionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aft.RoleSync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    boolean hasPos();
    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    com.jokerbee.protocol.Game.PositionInfo getPos();
    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder();
  }
  /**
   * Protobuf type {@code aft.RoleSync}
   */
  public  static final class RoleSync extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aft.RoleSync)
      RoleSyncOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoleSync.newBuilder() to construct.
    private RoleSync(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleSync() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoleSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.jokerbee.protocol.Game.PositionInfo.Builder subBuilder = null;
              if (pos_ != null) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(com.jokerbee.protocol.Game.PositionInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jokerbee.protocol.Game.internal_static_aft_RoleSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jokerbee.protocol.Game.internal_static_aft_RoleSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jokerbee.protocol.Game.RoleSync.class, com.jokerbee.protocol.Game.RoleSync.Builder.class);
    }

    public static final int POS_FIELD_NUMBER = 1;
    private com.jokerbee.protocol.Game.PositionInfo pos_;
    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    public boolean hasPos() {
      return pos_ != null;
    }
    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    public com.jokerbee.protocol.Game.PositionInfo getPos() {
      return pos_ == null ? com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
    }
    /**
     * <code>.aft.PositionInfo pos = 1;</code>
     */
    public com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder() {
      return getPos();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pos_ != null) {
        output.writeMessage(1, getPos());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPos());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jokerbee.protocol.Game.RoleSync)) {
        return super.equals(obj);
      }
      com.jokerbee.protocol.Game.RoleSync other = (com.jokerbee.protocol.Game.RoleSync) obj;

      boolean result = true;
      result = result && (hasPos() == other.hasPos());
      if (hasPos()) {
        result = result && getPos()
            .equals(other.getPos());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jokerbee.protocol.Game.RoleSync prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aft.RoleSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aft.RoleSync)
        com.jokerbee.protocol.Game.RoleSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jokerbee.protocol.Game.RoleSync.class, com.jokerbee.protocol.Game.RoleSync.Builder.class);
      }

      // Construct using com.jokerbee.protocol.Game.RoleSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (posBuilder_ == null) {
          pos_ = null;
        } else {
          pos_ = null;
          posBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSync_descriptor;
      }

      public com.jokerbee.protocol.Game.RoleSync getDefaultInstanceForType() {
        return com.jokerbee.protocol.Game.RoleSync.getDefaultInstance();
      }

      public com.jokerbee.protocol.Game.RoleSync build() {
        com.jokerbee.protocol.Game.RoleSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jokerbee.protocol.Game.RoleSync buildPartial() {
        com.jokerbee.protocol.Game.RoleSync result = new com.jokerbee.protocol.Game.RoleSync(this);
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jokerbee.protocol.Game.RoleSync) {
          return mergeFrom((com.jokerbee.protocol.Game.RoleSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jokerbee.protocol.Game.RoleSync other) {
        if (other == com.jokerbee.protocol.Game.RoleSync.getDefaultInstance()) return this;
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jokerbee.protocol.Game.RoleSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jokerbee.protocol.Game.RoleSync) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.jokerbee.protocol.Game.PositionInfo pos_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder> posBuilder_;
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public boolean hasPos() {
        return posBuilder_ != null || pos_ != null;
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfo getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public Builder setPos(com.jokerbee.protocol.Game.PositionInfo value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public Builder setPos(
          com.jokerbee.protocol.Game.PositionInfo.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public Builder mergePos(com.jokerbee.protocol.Game.PositionInfo value) {
        if (posBuilder_ == null) {
          if (pos_ != null) {
            pos_ =
              com.jokerbee.protocol.Game.PositionInfo.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = null;
          onChanged();
        } else {
          pos_ = null;
          posBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfo.Builder getPosBuilder() {
        
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
        }
      }
      /**
       * <code>.aft.PositionInfo pos = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aft.RoleSync)
    }

    // @@protoc_insertion_point(class_scope:aft.RoleSync)
    private static final com.jokerbee.protocol.Game.RoleSync DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jokerbee.protocol.Game.RoleSync();
    }

    public static com.jokerbee.protocol.Game.RoleSync getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleSync>
        PARSER = new com.google.protobuf.AbstractParser<RoleSync>() {
      public RoleSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleSync(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleSync> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleSync> getParserForType() {
      return PARSER;
    }

    public com.jokerbee.protocol.Game.RoleSync getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoleSyncRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:aft.RoleSyncResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string playerId = 1;</code>
     */
    java.lang.String getPlayerId();
    /**
     * <code>string playerId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    boolean hasPos();
    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    com.jokerbee.protocol.Game.PositionInfo getPos();
    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder();
  }
  /**
   * Protobuf type {@code aft.RoleSyncResp}
   */
  public  static final class RoleSyncResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:aft.RoleSyncResp)
      RoleSyncRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoleSyncResp.newBuilder() to construct.
    private RoleSyncResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoleSyncResp() {
      playerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoleSyncResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerId_ = s;
              break;
            }
            case 18: {
              com.jokerbee.protocol.Game.PositionInfo.Builder subBuilder = null;
              if (pos_ != null) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(com.jokerbee.protocol.Game.PositionInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jokerbee.protocol.Game.internal_static_aft_RoleSyncResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jokerbee.protocol.Game.internal_static_aft_RoleSyncResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jokerbee.protocol.Game.RoleSyncResp.class, com.jokerbee.protocol.Game.RoleSyncResp.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerId_;
    /**
     * <code>string playerId = 1;</code>
     */
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <code>string playerId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POS_FIELD_NUMBER = 2;
    private com.jokerbee.protocol.Game.PositionInfo pos_;
    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    public boolean hasPos() {
      return pos_ != null;
    }
    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    public com.jokerbee.protocol.Game.PositionInfo getPos() {
      return pos_ == null ? com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
    }
    /**
     * <code>.aft.PositionInfo pos = 2;</code>
     */
    public com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder() {
      return getPos();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerId_);
      }
      if (pos_ != null) {
        output.writeMessage(2, getPos());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerId_);
      }
      if (pos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPos());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jokerbee.protocol.Game.RoleSyncResp)) {
        return super.equals(obj);
      }
      com.jokerbee.protocol.Game.RoleSyncResp other = (com.jokerbee.protocol.Game.RoleSyncResp) obj;

      boolean result = true;
      result = result && getPlayerId()
          .equals(other.getPlayerId());
      result = result && (hasPos() == other.hasPos());
      if (hasPos()) {
        result = result && getPos()
            .equals(other.getPos());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jokerbee.protocol.Game.RoleSyncResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jokerbee.protocol.Game.RoleSyncResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code aft.RoleSyncResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:aft.RoleSyncResp)
        com.jokerbee.protocol.Game.RoleSyncRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSyncResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSyncResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jokerbee.protocol.Game.RoleSyncResp.class, com.jokerbee.protocol.Game.RoleSyncResp.Builder.class);
      }

      // Construct using com.jokerbee.protocol.Game.RoleSyncResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        playerId_ = "";

        if (posBuilder_ == null) {
          pos_ = null;
        } else {
          pos_ = null;
          posBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jokerbee.protocol.Game.internal_static_aft_RoleSyncResp_descriptor;
      }

      public com.jokerbee.protocol.Game.RoleSyncResp getDefaultInstanceForType() {
        return com.jokerbee.protocol.Game.RoleSyncResp.getDefaultInstance();
      }

      public com.jokerbee.protocol.Game.RoleSyncResp build() {
        com.jokerbee.protocol.Game.RoleSyncResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jokerbee.protocol.Game.RoleSyncResp buildPartial() {
        com.jokerbee.protocol.Game.RoleSyncResp result = new com.jokerbee.protocol.Game.RoleSyncResp(this);
        result.playerId_ = playerId_;
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jokerbee.protocol.Game.RoleSyncResp) {
          return mergeFrom((com.jokerbee.protocol.Game.RoleSyncResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jokerbee.protocol.Game.RoleSyncResp other) {
        if (other == com.jokerbee.protocol.Game.RoleSyncResp.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          onChanged();
        }
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jokerbee.protocol.Game.RoleSyncResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jokerbee.protocol.Game.RoleSyncResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerId_ = "";
      /**
       * <code>string playerId = 1;</code>
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = getDefaultInstance().getPlayerId();
        onChanged();
        return this;
      }
      /**
       * <code>string playerId = 1;</code>
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerId_ = value;
        onChanged();
        return this;
      }

      private com.jokerbee.protocol.Game.PositionInfo pos_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder> posBuilder_;
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public boolean hasPos() {
        return posBuilder_ != null || pos_ != null;
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfo getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public Builder setPos(com.jokerbee.protocol.Game.PositionInfo value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public Builder setPos(
          com.jokerbee.protocol.Game.PositionInfo.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public Builder mergePos(com.jokerbee.protocol.Game.PositionInfo value) {
        if (posBuilder_ == null) {
          if (pos_ != null) {
            pos_ =
              com.jokerbee.protocol.Game.PositionInfo.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = null;
          onChanged();
        } else {
          pos_ = null;
          posBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfo.Builder getPosBuilder() {
        
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      public com.jokerbee.protocol.Game.PositionInfoOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              com.jokerbee.protocol.Game.PositionInfo.getDefaultInstance() : pos_;
        }
      }
      /**
       * <code>.aft.PositionInfo pos = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.jokerbee.protocol.Game.PositionInfo, com.jokerbee.protocol.Game.PositionInfo.Builder, com.jokerbee.protocol.Game.PositionInfoOrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:aft.RoleSyncResp)
    }

    // @@protoc_insertion_point(class_scope:aft.RoleSyncResp)
    private static final com.jokerbee.protocol.Game.RoleSyncResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jokerbee.protocol.Game.RoleSyncResp();
    }

    public static com.jokerbee.protocol.Game.RoleSyncResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoleSyncResp>
        PARSER = new com.google.protobuf.AbstractParser<RoleSyncResp>() {
      public RoleSyncResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoleSyncResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoleSyncResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoleSyncResp> getParserForType() {
      return PARSER;
    }

    public com.jokerbee.protocol.Game.RoleSyncResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aft_PlayerLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aft_PlayerLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aft_PositionInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aft_PositionInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aft_RoleSync_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aft_RoleSync_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aft_RoleSyncResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aft_RoleSyncResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022\003aft\"0\n\013PlayerLogin\022\017\n\007acco" +
      "unt\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\":\n\014PositionI" +
      "nfo\022\014\n\004posX\030\001 \001(\005\022\014\n\004posY\030\002 \001(\005\022\016\n\006faceT" +
      "o\030\003 \001(\005\"*\n\010RoleSync\022\036\n\003pos\030\001 \001(\0132\021.aft.P" +
      "ositionInfo\"@\n\014RoleSyncResp\022\020\n\010playerId\030" +
      "\001 \001(\t\022\036\n\003pos\030\002 \001(\0132\021.aft.PositionInfoB\035\n" +
      "\025com.jokerbee.protocolB\004Gameb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_aft_PlayerLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aft_PlayerLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aft_PlayerLogin_descriptor,
        new java.lang.String[] { "Account", "Password", });
    internal_static_aft_PositionInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aft_PositionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aft_PositionInfo_descriptor,
        new java.lang.String[] { "PosX", "PosY", "FaceTo", });
    internal_static_aft_RoleSync_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aft_RoleSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aft_RoleSync_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_aft_RoleSyncResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aft_RoleSyncResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aft_RoleSyncResp_descriptor,
        new java.lang.String[] { "PlayerId", "Pos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
