// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageCode.proto

package com.jokerbee.protocol;

public final class MessageCode {
  private MessageCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息code
   * </pre>
   *
   * Protobuf enum {@code Code}
   */
  public enum Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UN_KNOW = 0;</code>
     */
    UN_KNOW(0),
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>MESSAGE_ERROR = 101;</code>
     */
    MESSAGE_ERROR(101),
    /**
     * <pre>
     * 账号登录
     * </pre>
     *
     * <code>CS_ACCOUNT_LOGIN = 1001;</code>
     */
    CS_ACCOUNT_LOGIN(1001),
    /**
     * <code>SC_ACCOUNT_LOGIN = 1002;</code>
     */
    SC_ACCOUNT_LOGIN(1002),
    /**
     * <pre>
     * 玩家登录
     * </pre>
     *
     * <code>CS_PLAYER_LOGIN = 1003;</code>
     */
    CS_PLAYER_LOGIN(1003),
    /**
     * <code>SC_PLAYER_LOGIN = 1004;</code>
     */
    SC_PLAYER_LOGIN(1004),
    /**
     * <code>CS_GET_BASE_INFO = 1005;</code>
     */
    CS_GET_BASE_INFO(1005),
    /**
     * <code>SC_GET_BASE_INFO = 1006;</code>
     */
    SC_GET_BASE_INFO(1006),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UN_KNOW = 0;</code>
     */
    public static final int UN_KNOW_VALUE = 0;
    /**
     * <pre>
     * 错误
     * </pre>
     *
     * <code>MESSAGE_ERROR = 101;</code>
     */
    public static final int MESSAGE_ERROR_VALUE = 101;
    /**
     * <pre>
     * 账号登录
     * </pre>
     *
     * <code>CS_ACCOUNT_LOGIN = 1001;</code>
     */
    public static final int CS_ACCOUNT_LOGIN_VALUE = 1001;
    /**
     * <code>SC_ACCOUNT_LOGIN = 1002;</code>
     */
    public static final int SC_ACCOUNT_LOGIN_VALUE = 1002;
    /**
     * <pre>
     * 玩家登录
     * </pre>
     *
     * <code>CS_PLAYER_LOGIN = 1003;</code>
     */
    public static final int CS_PLAYER_LOGIN_VALUE = 1003;
    /**
     * <code>SC_PLAYER_LOGIN = 1004;</code>
     */
    public static final int SC_PLAYER_LOGIN_VALUE = 1004;
    /**
     * <code>CS_GET_BASE_INFO = 1005;</code>
     */
    public static final int CS_GET_BASE_INFO_VALUE = 1005;
    /**
     * <code>SC_GET_BASE_INFO = 1006;</code>
     */
    public static final int SC_GET_BASE_INFO_VALUE = 1006;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Code valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Code forNumber(int value) {
      switch (value) {
        case 0: return UN_KNOW;
        case 101: return MESSAGE_ERROR;
        case 1001: return CS_ACCOUNT_LOGIN;
        case 1002: return SC_ACCOUNT_LOGIN;
        case 1003: return CS_PLAYER_LOGIN;
        case 1004: return SC_PLAYER_LOGIN;
        case 1005: return CS_GET_BASE_INFO;
        case 1006: return SC_GET_BASE_INFO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Code>() {
            public Code findValueByNumber(int number) {
              return Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jokerbee.protocol.MessageCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Code)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MessageCode.proto*\256\001\n\004Code\022\013\n\007UN_KNOW\020" +
      "\000\022\021\n\rMESSAGE_ERROR\020e\022\025\n\020CS_ACCOUNT_LOGIN" +
      "\020\351\007\022\025\n\020SC_ACCOUNT_LOGIN\020\352\007\022\024\n\017CS_PLAYER_" +
      "LOGIN\020\353\007\022\024\n\017SC_PLAYER_LOGIN\020\354\007\022\025\n\020CS_GET" +
      "_BASE_INFO\020\355\007\022\025\n\020SC_GET_BASE_INFO\020\356\007B$\n\025" +
      "com.jokerbee.protocolB\013MessageCodeb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
